#!/bin/bash

set -e

OPTIONS_SPEC="git-ffwd [options] <branch1> <branch2...>

forward-ports branches on top of current branch.
you must have the new upstream branch already checked out.
--
s,squash  forward-port all commits as one squash commit
a,all     forward-port all local branches
"
SUBDIRECTORY_OK=1
. "$(git --exec-path)/git-sh-setup"
set_reflog_action ffwd
require_work_tree

ffwd_branch() {
  branch=$1

  echo "Processing $branch..."
  # Get off the current branch, if any.
  git checkout -q HEAD^{}

  if [ "$squash" ]; then
    echo "TODO: squashing not implemented"
  else
    for rev in $(git rev-list --reverse $branch ^HEAD); do
      echo $rev
      git cherry-pick $rev > /dev/null
    done
  fi

  echo "Clobbering your old branch; use 'git reflog' to recover if something goes wrong!"
  git update-ref refs/heads/$branch HEAD
}

squash=
all=
while test $# != 0; do
  case "$1" in
    -s)
      squash=1
      echo "TODO: squashing not implemented"
      exit 1
      ;;
    -a)
      all=1
      echo "TODO: all not implemented"
      exit 1
      ;;
    --)
      shift
      break
      ;;
  esac
  shift
done

if [ $# = 0 ]; then
  usage
fi

while [ $# != 0 ]; do
  ffwd_branch $1
  shift
done
